name: 'actions-download-zip'
description: 'Download a released zip'
inputs:
  version:
    description: 'The version to download. E.g. 3.14.0'
    default: ''
  package-name:
    description: 'Name of the package (e.g. boost_1_74_0)'
    default: ''
  env-var-name:
    description: 'Name of the export environment (e.g. BOOST_DIR_2019)'
    default: ''
  releases-url:
    description: 'Url of the releases (e.g. https://api.github.com/repos/_org_/_repo_/releases)'
    default: ''
  github-api-token:
    description: 'GitHub token to use when retrieving version info'
    default: '${{ github.token }}'
  force-reinstall:
    description: 'Ignore the cached value and reinstall the package'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
